name: Test and Build

on:
  push:
    branches:
      - main

jobs:
  Test_and_Build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build Sources
        run: npm run build
      - name: Publish to NPM
        if: startsWith(github.ref,'refs/tags/')
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish
      - name: Compile Release
        if: startsWith(github.ref,'refs/tags/')
        run: npm run compile
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref,'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Artifacts"
          files: |
            artifacts/envshell-linux
            artifacts/envshell-win.exe
